-- Auto generated by FGUICsToLuaGenerator. Do not modify.
-- Source: Assets/Scripts/FGUI/Common/Common/UI_CommonTest.cs

UI_CommonTest = setmetatable({}, FGUIPanel)
UI_CommonTest.__index = UI_CommonTest

UI_CommonTest.URL = "ui://rovr2x2qe0871"
UI_CommonTest.PKG = "Common"
UI_CommonTest.RES = "CommonTest"

function UI_CommonTest.Create()
    return FGUIPanel.Create(UI_CommonTest, UI_CommonTest.PKG, UI_CommonTest.RES)
end

function UI_CommonTest:OnInit(view)
    self.m_commonText = view:GetChildAt(1)
end

FGUIPanel.RegisterExtension(UI_CommonTest)

