-- Auto generated by FGUICsToLuaGenerator. Do not modify.
-- Source: Assets/Scripts/FGUI/Common/Common/UI_PopupMask.cs

UI_PopupMask = setmetatable({}, FGUIPanel)
UI_PopupMask.__index = UI_PopupMask

UI_PopupMask.URL = "ui://rovr2x2qn7im3"
UI_PopupMask.PKG = "Common"
UI_PopupMask.RES = "PopupMask"

function UI_PopupMask.Create()
    return FGUIPanel.Create(UI_PopupMask, UI_PopupMask.PKG, UI_PopupMask.RES)
end

function UI_PopupMask:OnInit(view)
    self.m_mask = view:GetChildAt(0)
end

FGUIPanel.RegisterExtension(UI_PopupMask)

