-- Auto generated by FGUICsToLuaGenerator. Do not modify.
-- Source: Assets/Scripts/FGUI/PopupTest/PopupTest/UI_PopupTest.cs

UI_PopupTest = setmetatable({}, FGUIPanel)
UI_PopupTest.__index = UI_PopupTest

UI_PopupTest.URL = "ui://pac0obpbn7im0"
UI_PopupTest.PKG = "PopupTest"
UI_PopupTest.RES = "PopupTest"

function UI_PopupTest.Create()
    return FGUIPanel.Create(UI_PopupTest, UI_PopupTest.PKG, UI_PopupTest.RES)
end

function UI_PopupTest:OnInit(view)
    self.m_closeBtn = view:GetChildAt(2)
end

FGUIPanel.RegisterExtension(UI_PopupTest)

