-- Auto generated by FGUICsToLuaGenerator. Do not modify.
-- Source: Assets/Scripts/FGUI/Home/Home/UI_HomePanel.cs

UI_Home = setmetatable({}, FGUIPanel)
UI_Home.__index = UI_Home

UI_Home.URL = "ui://p20zd5lye0870"
UI_Home.PKG = "Home"
UI_Home.RES = "HomePanel"

function UI_Home.Create()
    return FGUIPanel.Create(UI_Home, UI_Home.PKG, UI_Home.RES)
end

function UI_Home:OnInit(view)
    self.m_popupTest = view:GetChildAt(1)
    self.m_Ripple = view:GetChildAt(2)
    self.m_text1 = view:GetChildAt(3)
    self.m_text2 = view:GetChildAt(4)
    self.m_DeerRoot = view:GetChildAt(8)
end

FGUIPanel.RegisterExtension(UI_Home)

