-- Auto generated by FGUICsToLuaGenerator. Do not modify.
-- Source: Assets/Scripts/FGUI/GameLoading/GameLoading/UI_GameLoadingPanel.cs

UI_GameLoading = setmetatable({}, FGUIPanel)
UI_GameLoading.__index = UI_GameLoading

UI_GameLoading.URL = "ui://rcpqb2f6wuau0"
UI_GameLoading.PKG = "GameLoading"
UI_GameLoading.RES = "GameLoadingPanel"

function UI_GameLoading.Create()
    return FGUIPanel.Create(UI_GameLoading, UI_GameLoading.PKG, UI_GameLoading.RES)
end

function UI_GameLoading:OnInit(view)
    self.m_bar = view:GetChildAt(2)
    self.m_test1 = view:GetChildAt(3)
    self.m_test2 = view:GetChildAt(4)
    self.m_test3 = view:GetChildAt(5)
end

FGUIPanel.RegisterExtension(UI_GameLoading)

